-- Tabelas para o Sistema Mixbarato

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  category TEXT NOT NULL REFERENCES categories(name) ON UPDATE CASCADE,
  "desc" TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  code TEXT,
  stock BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir Categorias Iniciais
INSERT INTO categories (name) VALUES ('Utilidades'), ('Eletrônicos'), ('Presentes'), ('Decoração');